# 소셜네트워크 이론과 응용 
## Google Matrix 예제 
- 웹 중요도 Google Matrix를 이용하여 계산 (그림: N20Q_Q3_How does Google rank web pages.pdf 파일 28p)
- no dangling node, 확률 0.85

In [1]:
import numpy as np

In [2]:
H = np.array([
    [0, 1/2, 1/2, 0, 0, 0, 0, 0],
    [1/2, 0, 0, 0, 1/2, 0, 0 ,0],
    [0, 1/2, 0, 0, 0, 0, 0, 1/2],
    [0, 0, 1, 0, 0, 0, 0, 0],
    [0, 0, 0, 1/2, 0, 0, 0, 1/2],
    [0, 0, 0, 1/2, 1/2, 0, 0, 0],
    [0, 0, 0, 1/2, 0, 1/2, 0, 0],
    [1/3, 0, 0, 1/3, 0, 0, 1/3, 0]
])

In [3]:
H.shape

(8, 8)

In [4]:
np.ones((8,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [5]:
G = 0.85 * H + 0.15 / 8 * np.ones((8,8))

In [6]:
G

array([[0.01875   , 0.44375   , 0.44375   , 0.01875   , 0.01875   ,
        0.01875   , 0.01875   , 0.01875   ],
       [0.44375   , 0.01875   , 0.01875   , 0.01875   , 0.44375   ,
        0.01875   , 0.01875   , 0.01875   ],
       [0.01875   , 0.44375   , 0.01875   , 0.01875   , 0.01875   ,
        0.01875   , 0.01875   , 0.44375   ],
       [0.01875   , 0.01875   , 0.86875   , 0.01875   , 0.01875   ,
        0.01875   , 0.01875   , 0.01875   ],
       [0.01875   , 0.01875   , 0.01875   , 0.44375   , 0.01875   ,
        0.01875   , 0.01875   , 0.44375   ],
       [0.01875   , 0.01875   , 0.01875   , 0.44375   , 0.44375   ,
        0.01875   , 0.01875   , 0.01875   ],
       [0.01875   , 0.01875   , 0.01875   , 0.44375   , 0.01875   ,
        0.44375   , 0.01875   , 0.01875   ],
       [0.30208333, 0.01875   , 0.01875   , 0.30208333, 0.01875   ,
        0.01875   , 0.30208333, 0.01875   ]])

In [7]:
init = [1/8,1/8,1/8,1/8,1/8,1/8,1/8,1/8] 

In [8]:
ans = init@G
ans

array([0.10729167, 0.125     , 0.178125  , 0.21354167, 0.125     ,
       0.071875  , 0.05416667, 0.125     ])

In [9]:
ans = ans@G
ans

array([0.10729167, 0.14005208, 0.24585937, 0.16085937, 0.10242188,
       0.04177083, 0.05416667, 0.14757813])

In [10]:
ans = ans@G
ans

array([0.12008594, 0.16883919, 0.20107943, 0.14486654, 0.09602474,
       0.04177083, 0.0605638 , 0.16676953])

In [11]:
ans = ans@G
ans

array([0.13775802, 0.15524528, 0.19292308, 0.1503041 , 0.10825926,
       0.04448962, 0.06600137, 0.14501927])

In [12]:
ans = ans@G
ans

array([0.12581804, 0.15928947, 0.20505565, 0.15280765, 0.10363733,
       0.04680058, 0.05983879, 0.14675249])

In [13]:
ans = ans@G
ans

array([0.1280279 , 0.15937132, 0.20210917, 0.14969747, 0.10633827,
       0.04418149, 0.06032987, 0.14994452])

In [14]:
ans = ans@G
ans

array([0.12896709, 0.15905825, 0.20040471, 0.15084537, 0.10525994,
       0.0443902 , 0.06123428, 0.14984016])

In [15]:
ans = ans@G
ans

array([0.12880447, 0.15873301, 0.20177958, 0.15083059, 0.10521559,
       0.04477457, 0.06120471, 0.14865748])

In [16]:
ans = ans@G
ans

array([0.12833115, 0.15924822, 0.2016979 , 0.15062744, 0.10524072,
       0.044762  , 0.06086962, 0.14922295])

In [17]:
ans = ans@G
ans

array([0.12871033, 0.15901235, 0.20132406, 0.15065058, 0.10545434,
       0.04461959, 0.06102984, 0.14919891])

In [18]:
ans = ans@G
ans

array([0.12860327, 0.15901462, 0.20150488, 0.15074213, 0.10529357,
       0.04468768, 0.06102303, 0.14913082])

In [19]:
ans = ans@G
ans

array([0.12858494, 0.15904597, 0.2015372 , 0.15068055, 0.10532348,
       0.04468479, 0.06100373, 0.14913934])

In [20]:
ans = ans@G
ans

array([0.12860068, 0.15905191, 0.20147707, 0.15068625, 0.10533557,
       0.04467659, 0.06100615, 0.14916579])

In [26]:
ans = ans@G
ans

array([0.1286015 , 0.1590412 , 0.20149461, 0.15069247, 0.10533091,
       0.04467901, 0.06100924, 0.14915107])

In [27]:
ans = ans@G
ans

array([0.12860198, 0.15904085, 0.20149424, 0.15069261, 0.10533109,
       0.04467893, 0.06100947, 0.14915084])

In [28]:
ans = ans@G
ans

array([0.12860177, 0.15904089, 0.20149456, 0.15069269, 0.1053309 ,
       0.04467902, 0.06100941, 0.14915076])

In [29]:
ans = ans@G
ans

array([0.12860176, 0.15904094, 0.20149453, 0.1506926 , 0.10533096,
       0.044679  , 0.06100938, 0.14915082])

In [30]:
ans = ans@G
ans

array([0.1286018 , 0.15904093, 0.20149446, 0.15069262, 0.10533097,
       0.04467899, 0.0610094 , 0.14915084])

In [31]:
ans = ans@G
ans

array([0.1286018 , 0.15904091, 0.20149449, 0.15069263, 0.10533096,
       0.04467899, 0.0610094 , 0.14915081])

In [32]:
ans = ans@G
ans

array([0.12860178, 0.15904092, 0.2014945 , 0.15069262, 0.10533096,
       0.044679  , 0.0610094 , 0.14915082])

In [33]:
ans = ans@G
ans

array([0.12860179, 0.15904092, 0.20149449, 0.15069262, 0.10533097,
       0.04467899, 0.0610094 , 0.14915082])

In [34]:
ans = ans@G
ans

array([0.12860179, 0.15904092, 0.20149449, 0.15069263, 0.10533096,
       0.04467899, 0.0610094 , 0.14915082])

In [41]:
ans = ans@G
ans

array([0.12860179, 0.15904092, 0.20149449, 0.15069262, 0.10533096,
       0.04467899, 0.0610094 , 0.14915082])

결론 : [0.1286, 0.1590, 0.2015, 0.1507, 0.1053,
       0.0447, 0.0610 , 0.1492]로, 
       웹페이지 중요도 순서는 3->2->4->8->1->5->7->6