# 소셜네트워크 이론과 응용 
## Node Importance - Centralities  

In [31]:
import numpy as np

In [32]:
arr = np.array(
    [
        [0, 1, 1, 1, 0, 0, 0, 0],
        [1, 0, 0, 1, 1, 0, 0, 0],
        [1, 0, 0, 0, 0, 1, 1, 1],
        [1, 1, 0, 0, 1, 0, 0, 0],
        [0, 1, 0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 1, 0, 1],
        [0, 0, 1, 0, 0, 0, 1, 0]
])

## Eigenvector centrality

In [33]:
arr.shape

(8, 8)

In [34]:
e_vec = np.random.rand(arr.shape[0]) # 8개 식
e_value = 1.0
e_vec

array([0.59111965, 0.73931797, 0.317461  , 0.86364972, 0.78832582,
       0.96324443, 0.67261484, 0.68147964])

In [35]:
# iteration 반복
while True:
    eig_vec = np.dot(arr, e_vec)
    eig_value = max(abs(eig_vec))
    eig_vec = eig_vec / eig_value

    stop_condition = abs(eig_value - e_value)
    if stop_condition <= 1e-8:
        break
    else:
        e_vec = eig_vec
        e_value = eig_value

e_vec = e_vec / np.linalg.norm(e_vec)

print("*** Eigenvector centrality ***")
print("Eigen Value : ", e_value)
print("Eigen Vector : ", e_vec)

*** Eigenvector centrality ***
Eigen Value :  2.872276267492233
Eigen Vector :  [0.40631621 0.34551749 0.4760174  0.34551749 0.24058793 0.29492471
 0.37108784 0.29492471]


## Closeness centrality

In [36]:
def get_distances_matrix(arr, i, j, path=[]):
    path = path + [i]
    if i == j:
        return path
    if i not in graph:
        return None

    shortest = None
    for node in graph[i]:
        if node not in path:
            new_path = get_distances_matrix(arr, node, j, path)
            if new_path:
                if not shortest or len(new_path) < len(shortest):
                    shortest = new_path
    return shortest

In [37]:
#hash
D_matrix = np.copy(arr)
graph = {}
for i in range(arr.shape[0]):
    seen = []
    for j in range(arr.shape[0]):
        if arr[i][j] == 1:
            seen.append(j)
    graph[i] = seen

for i in range(arr.shape[0]):
    for j in range(arr.shape[0]):
        if i != j:
            if D_matrix[i][j] != 1:
                D_matrix[i][j] = len(get_distances_matrix(graph, i, j)) - 1

print(D_matrix)

[[0 1 1 1 2 2 2 2]
 [1 0 2 1 1 3 3 3]
 [1 2 0 2 3 1 1 1]
 [1 1 2 0 1 3 3 3]
 [2 1 3 1 0 4 4 4]
 [2 3 1 3 4 0 1 2]
 [2 3 1 3 4 1 0 1]
 [2 3 1 3 4 2 1 0]]


In [39]:
print("*** Closeness centrality ***")
for i in range(D_matrix.shape[0]):
    val = (D_matrix.shape[0] - 1) / np.sum(D_matrix[i])
    print("C{} = {}".format(i+1, round(val,4)))

*** Closeness centrality ***
C1 = 0.6364
C2 = 0.5
C3 = 0.6364
C4 = 0.5
C5 = 0.3684
C6 = 0.4375
C7 = 0.4667
C8 = 0.4375
